# This is a config for E2B sandbox template.
# You can use template ID (p5k5dwtrjddjzyjqird9) or template name (codeHaus-nextjs-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("codeHaus-nextjs-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("codeHaus-nextjs-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('codeHaus-nextjs-test')

team_id = "23a17934-0616-4fc4-8151-606dc4e365b7"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "codeHaus-nextjs-test"
template_id = "p5k5dwtrjddjzyjqird9"
